### PR TITLE
THX-35487 include aspects from jar

### LINKED ISSUE #5: THX-35487 Include Aspects from Jar does not work with Java8 Enabled App
STR:

- Create a java8 enabled Android app.
- Create a jar with compiled aspects that log to the console (logcat) for visibility.
- Configure the java8 app to use the AJ `ext` plugin.
- Configure the java8 AJ closure to include aspects from jars using the jar names from step 2.
- Run the app.
**Result** 
Aspects are not woven and no logs occur.
**Expected**
Aspects are woven and logs occur.

Note: Java6 enabled Android apps are not affected. Local AJ files are not affected.

### PR DESCRIPTION
**Pull request by JustinTullgren**
Replace javac output with AJ output when in Java8 Enabled project so the sources are woven before it goes to the transform api and skip the transform all together.  We do this because the transform chain invokes the desugar tool first which messes with the pre compiled aspect byte code constant string pool thus not allowing the transformer to complete the aj weave successfully.  See this [google bug](https://issuetracker.google.com/u/0/issues/119153999)

resolve #5

### CODE REVIEW

File: android-gradle-plugin-aspectj/src/main/kotlin/com/archinamon/api/AspectJCompileTask.kt [hunk 1]
```diff
@@ -22,32 +23,30 @@ import com.archinamon.AspectJExtension
...
+import org.gradle.api.internal.ConventionTask
 import org.gradle.api.internal.file.collections.SimpleFileCollection
 import org.gradle.api.tasks.TaskAction
-import org.gradle.api.tasks.compile.AbstractCompile
 import org.gradle.api.tasks.compile.JavaCompile
 import java.io.File
 import java.util.*
 
-internal open class AspectJCompileTask : AbstractCompile() {
+// TODO: This task doesn't do incremental builds. Is that problem?
```
Comment (JustinTullgren) [inline android-gradle-plugin-aspectj/src/main/kotlin/com/archinamon/api/AspectJCompileTask.kt]: it doesn't appear to be a problem. remove.

File: android-gradle-plugin-aspectj/src/main/kotlin/com/archinamon/api/AspectJCompileTask.kt [hunk 2]
```diff
@@ -132,31 +135,52 @@ internal open class AspectJCompileTask : AbstractCompile() {
...
-
-            classpath.forEach { file ->
-                if (aspectsFromJar.isNotEmpty() && DependencyFilter.isIncludeFilterMatched(file, aspectsFromJar)) {
-                    logJarAspectAdded(file)
-                    aspects shl file
+            val classpath = task.classpath
+            if (classpath != null) {
+                val aspects: MutableSet<File> = mutableSetOf()
+
+                classpath.forEach { file ->
```
Comment (JustinTullgren) [inline android-gradle-plugin-aspectj/src/main/kotlin/com/archinamon/api/AspectJCompileTask.kt:142]: no need to iterate if aspectsFromJar is empty. pull the condition up.

File: android-gradle-plugin-aspectj/src/main/kotlin/com/archinamon/api/AspectJCompileTask.kt [hunk 3]
```diff
@@ -132,31 +135,52 @@ internal open class AspectJCompileTask : AbstractCompile() {
...
         private fun findCompiledAspectsInClasspath(task: AspectJCompileTask, aspectsFromJar: Collection<String>) {
-            val classpath: FileCollection = task.classpath
-            val aspects: MutableSet<File> = mutableSetOf()
-
-            classpath.forEach { file ->
-                if (aspectsFromJar.isNotEmpty() && DependencyFilter.isIncludeFilterMatched(file, aspectsFromJar)) {
-                    logJarAspectAdded(file)
-                    aspects shl file
+            val classpath = task.classpath
+            if (classpath != null && aspectsFromJar.isNotEmpty()) {
```
Comment (andreipop) [inline android-gradle-plugin-aspectj/src/main/kotlin/com/archinamon/api/AspectJCompileTask.kt:139]: Are we logging somewhere if this is null or empty?

Comment (JustinTullgren) [reply android-gradle-plugin-aspectj/src/main/kotlin/com/archinamon/api/AspectJCompileTask.kt:139]: if classpath is null it gets handled later at the compile task action. no need to log the empty unless you want to but maybe if we had different logging levels it might be okay but we dont.

**Review by andreipop — APPROVED** [review]

**Review by ghost — APPROVED** [review]
